// Code generated by protoc-gen-go. DO NOT EDIT.
// source: car.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCarRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCarRequest) Reset()         { *m = GetCarRequest{} }
func (m *GetCarRequest) String() string { return proto.CompactTextString(m) }
func (*GetCarRequest) ProtoMessage()    {}
func (*GetCarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_db3dd3b0323a196b, []int{0}
}
func (m *GetCarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCarRequest.Unmarshal(m, b)
}
func (m *GetCarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCarRequest.Marshal(b, m, deterministic)
}
func (dst *GetCarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCarRequest.Merge(dst, src)
}
func (m *GetCarRequest) XXX_Size() int {
	return xxx_messageInfo_GetCarRequest.Size(m)
}
func (m *GetCarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCarRequest proto.InternalMessageInfo

func (m *GetCarRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateCarRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Manifacturer         string   `protobuf:"bytes,2,opt,name=manifacturer,proto3" json:"manifacturer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCarRequest) Reset()         { *m = CreateCarRequest{} }
func (m *CreateCarRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCarRequest) ProtoMessage()    {}
func (*CreateCarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_db3dd3b0323a196b, []int{1}
}
func (m *CreateCarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCarRequest.Unmarshal(m, b)
}
func (m *CreateCarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCarRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCarRequest.Merge(dst, src)
}
func (m *CreateCarRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCarRequest.Size(m)
}
func (m *CreateCarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCarRequest proto.InternalMessageInfo

func (m *CreateCarRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCarRequest) GetManifacturer() string {
	if m != nil {
		return m.Manifacturer
	}
	return ""
}

type CarResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Manifacturer         string   `protobuf:"bytes,3,opt,name=manifacturer,proto3" json:"manifacturer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarResponse) Reset()         { *m = CarResponse{} }
func (m *CarResponse) String() string { return proto.CompactTextString(m) }
func (*CarResponse) ProtoMessage()    {}
func (*CarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_db3dd3b0323a196b, []int{2}
}
func (m *CarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarResponse.Unmarshal(m, b)
}
func (m *CarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarResponse.Marshal(b, m, deterministic)
}
func (dst *CarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarResponse.Merge(dst, src)
}
func (m *CarResponse) XXX_Size() int {
	return xxx_messageInfo_CarResponse.Size(m)
}
func (m *CarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CarResponse proto.InternalMessageInfo

func (m *CarResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CarResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CarResponse) GetManifacturer() string {
	if m != nil {
		return m.Manifacturer
	}
	return ""
}

func init() {
	proto.RegisterType((*GetCarRequest)(nil), "pb.GetCarRequest")
	proto.RegisterType((*CreateCarRequest)(nil), "pb.CreateCarRequest")
	proto.RegisterType((*CarResponse)(nil), "pb.CarResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CarClient is the client API for Car service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarClient interface {
	GetCar(ctx context.Context, in *GetCarRequest, opts ...grpc.CallOption) (*CarResponse, error)
	CreateCar(ctx context.Context, in *CreateCarRequest, opts ...grpc.CallOption) (*CarResponse, error)
}

type carClient struct {
	cc *grpc.ClientConn
}

func NewCarClient(cc *grpc.ClientConn) CarClient {
	return &carClient{cc}
}

func (c *carClient) GetCar(ctx context.Context, in *GetCarRequest, opts ...grpc.CallOption) (*CarResponse, error) {
	out := new(CarResponse)
	err := c.cc.Invoke(ctx, "/pb.Car/GetCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carClient) CreateCar(ctx context.Context, in *CreateCarRequest, opts ...grpc.CallOption) (*CarResponse, error) {
	out := new(CarResponse)
	err := c.cc.Invoke(ctx, "/pb.Car/CreateCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarServer is the server API for Car service.
type CarServer interface {
	GetCar(context.Context, *GetCarRequest) (*CarResponse, error)
	CreateCar(context.Context, *CreateCarRequest) (*CarResponse, error)
}

func RegisterCarServer(s *grpc.Server, srv CarServer) {
	s.RegisterService(&_Car_serviceDesc, srv)
}

func _Car_GetCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServer).GetCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Car/GetCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServer).GetCar(ctx, req.(*GetCarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Car_CreateCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServer).CreateCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Car/CreateCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServer).CreateCar(ctx, req.(*CreateCarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Car_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Car",
	HandlerType: (*CarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCar",
			Handler:    _Car_GetCar_Handler,
		},
		{
			MethodName: "CreateCar",
			Handler:    _Car_CreateCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car.proto",
}

func init() { proto.RegisterFile("car.proto", fileDescriptor_car_db3dd3b0323a196b) }

var fileDescriptor_car_db3dd3b0323a196b = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4e, 0x2c, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe7, 0xe2, 0x75, 0x4f, 0x2d,
	0x71, 0x4e, 0x2c, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x51, 0xf2, 0xe2, 0x12, 0x70, 0x2e,
	0x4a, 0x4d, 0x2c, 0x49, 0x45, 0x52, 0x23, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x0a, 0x56, 0xc5,
	0x19, 0x04, 0x66, 0x0b, 0x29, 0x71, 0xf1, 0xe4, 0x26, 0xe6, 0x65, 0xa6, 0x25, 0x26, 0x97, 0x94,
	0x16, 0xa5, 0x16, 0x49, 0x30, 0x81, 0xe5, 0x50, 0xc4, 0x94, 0x42, 0xb9, 0xb8, 0xc1, 0xa6, 0x14,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0xa2, 0x5b, 0x05, 0x37, 0x96, 0x09, 0x8f, 0xb1, 0xcc, 0x98, 0xc6,
	0x1a, 0x65, 0x73, 0x31, 0x3b, 0x27, 0x16, 0x09, 0xe9, 0x71, 0xb1, 0x41, 0xbc, 0x22, 0x24, 0xa8,
	0x57, 0x90, 0xa4, 0x87, 0xe2, 0x2d, 0x29, 0x7e, 0x90, 0x10, 0x92, 0xe5, 0x4a, 0x0c, 0x42, 0x26,
	0x5c, 0x9c, 0x70, 0x9f, 0x09, 0x89, 0x80, 0xe5, 0xd1, 0x3c, 0x8a, 0x45, 0x57, 0x12, 0x1b, 0x38,
	0xec, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x10, 0xbd, 0xc6, 0x6a, 0x48, 0x01, 0x00, 0x00,
}
